[project]
name = "championsbricks"
version = "0.1.0"
description = "POC Databricks Lakehouse for Champions League data ingestion"
authors = [{ name = "Geo Vaq" }]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "requests>=2.32.5",
]
